on: [push]

name: AzureRMDeploy

jobs:
    
    deploy:
      runs-on: ubuntu-latest
      steps:
    
      - name: login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VMACTIONSEC }}

      - name: checkout source code
        uses: actions/checkout@v1

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
           az deployment group create \
           --name VirtualMachineDeployment \
           --resource-group POC_DevOps_RG \
           --template-file storageaccount.json \
           --parameters virtualmachinename=prasanth-vm
