name: GitHub for IT Pro CI/CD Pipeline

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:
      
  # Deploy VM in Azure
  DeployVM:
    runs-on: windows-latest

    steps:
    
    - name: login to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.VMACTIONSEC }}
          
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    - name: look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'

    - name: provision virtual machine in azure
      env:
        RESOURCE_GROUP: rg-githubdeploy
        RESOURCE_GROUP_REGION: ukwest
        SERVER_NAME: githubactions
        ADMIN_LOGIN: sarah
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'" 
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 
        -serverName %SERVER_NAME% 
        -adminLogin %ADMIN_LOGIN% 
        -adminPassword ${{ secrets.ADMIN_PASSWORD }} 

