name: GitHub for IT Pro CI/CD Pipeline

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:
      
  # Deploy VM in Azure
  DeployVM:
    runs-on: windows-latest

    steps:
    
    - name: login to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.VMACTIONSEC }}
          
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    - name: look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'

    - name: provision virtual machine in azure
      env:
        RESOURCE_GROUP: myTestRG
        RESOURCE_GROUP_REGION: ukwest
        SERVER_NAME: githubactions
      run: >
       $UserName = "username"
       $Password = ConvertTo-SecureString "password@123" -AsPlainText -Force
       $psCred = New-Object System.Management.Automation.PSCredential($UserName, $Password)
       New-AzVm `
       -ResourceGroupName "myTestRG" `
       -Name "myTestVM" `
       -size "Standard_D2s_v3" `
       -Location "East US" `
       -VirtualNetworkName "myTestVnet" `
       -SubnetName "myTestSubnet" `
       -SecurityGroupName "myTestNSG" `
       -Credential $psCred `
       -PublicIpAddressName "myTestpip" `
       -OpenPorts 80,3389
   
